version: '3'
services:
  worker:
    env_file:
      - envs.env
    build: .
    ports:
      - 8000:8000
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: music_slack
    volumes:
      - ./db_data:/var/lib/mysql