version: '3'
services:
  worker:
    env_file:
      - envs.env
    build: ./backend
    ports:
      - 8000:8000

  frontend:
    build: ./slack-music-frontend
    ports:
      - 8001:80

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: music_slack
    volumes:
     - ./db_data:/var/lib/mysql